version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/fr.univavignon.pokedex.api
    steps:
      - checkout
      - run:
          name: Run Unit Tests with Maven
          command: mvn test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only: master

