machine:
  java:
    version: openjdk8
general:
  branches:
    only:
      - master

test:
  override:
    - mvn test
version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:8.0
    working_directory: ~/repo
    steps:
      - checkout
      - run: "Executing Unit Tests"
        command: "mvn test"

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only: master

